import { motion } from 'framer-motion'
import { Lightbulb } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import type { RecommendationItem } from '@/lib/types'

interface RecommendationsTabProps {
  items: RecommendationItem[]
}

const priorityVariant = {
  low: 'secondary' as const,
  medium: 'warning' as const,
  high: 'danger' as const,
  critical: 'danger' as const,
}

export function RecommendationsTab({ items }: RecommendationsTabProps) {
  if (items.length === 0) {
    return (
      <div className="flex h-40 items-center justify-center text-sm text-slate-500">
        Recommendations will be generated by the Recommendation Agent
      </div>
    )
  }

  return (
    <div className="space-y-3">
      {items.map((item, index) => (
        <motion.div
          key={item.id}
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: index * 0.05 }}
          className="flex gap-4 rounded-lg border border-white/10 bg-slate-950/40 p-4"
        >
          <div className="rounded-lg border border-amber-500/20 bg-amber-500/10 p-2 text-amber-400">
            <Lightbulb className="h-4 w-4" />
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2">
              <span className="text-sm font-medium text-slate-200">{item.title}</span>
              <Badge variant={priorityVariant[item.priority]}>{item.priority}</Badge>
            </div>
            <p className="mt-1 text-xs leading-relaxed text-slate-400">{item.description}</p>
          </div>
        </motion.div>
      ))}
    </div>
  )
}
